### ISSUE TITLE
One great app, but landscape images aren't perfect

### ISSUE THREAD

**Issue by Loschcode** [lpender/meteor-assets#1]
Hey man, great work on this, it's been a while i'm looking for a tool dedicated to Meteor, you're my savior right now.

Small bug tho, i've a centered icon on my splash screen but in the landscape version it put it on the bottom on all versions :(

![iphone6p_landscape](https://cloud.githubusercontent.com/assets/6666570/11382076/6b556eda-9308-11e5-8e59-3cd55645a668.png)

**UPDATE : I also noticed the AppStore refused my App. It seems there's a problem with the iPhone 5 splash screen generated. Looks weird on the emulator too (like the image isn't formatted correctly**

**Comment by lpender** [comment]
@Loschcode I've made some updates recently which I believe fix these issues.

Please give it another try and let me know if you still have issues.

Thanks
-Lee
