### ISSUE TITLE
Current set does not include a few key icons

### ISSUE THREAD

**Issue by adamgins** [lpender/meteor-assets#10]
I used the current set and Apple rejected it.

From what I can see 57x57 iPhone is missing

https://github.com/phonegap/phonegap/wiki/App-Icon-Sizes
Missing Splash:
<img width="332" alt="screen shot 2017-04-15 at 8 09 34 am" src="https://cloud.githubusercontent.com/assets/7233741/25057412/f3eadef8-21b2-11e7-8e0b-c7f4be5ac6c2.png">
Missing Icons:
<img width="261" alt="screen shot 2017-04-15 at 8 09 14 am" src="https://cloud.githubusercontent.com/assets/7233741/25057414/f3f14c16-21b2-11e7-8572-1bbe2d8c4229.png">
<img width="221" alt="screen shot 2017-04-15 at 8 08 54 am" src="https://cloud.githubusercontent.com/assets/7233741/25057413/f3ecd7a8-21b2-11e7-9a39-8c3ca0978eb7.png">

**Comment by lpender** [comment]
@adamgins the app can accept arbitrary values, I'll just need a new list that looks like this:


```
App.icons({
  "iphone_2x": "resources/icons/iphone_2x.png", // 120x120
  "iphone_3x": "resources/icons/iphone_3x.png", // 180x180
  "ipad": "resources/icons/ipad.png", // 76x76
  "ipad_2x": "resources/icons/ipad_2x.png", // 152x152
  "ipad_pro": "resources/icons/ipad_pro.png", // 167x167
  "ios_settings": "resources/icons/ios_settings.png", // 29x29
  "ios_settings_2x": "resources/icons/ios_settings_2x.png", // 58x58
  "ios_settings_3x": "resources/icons/ios_settings_3x.png", // 87x87
  "ios_spotlight": "resources/icons/ios_spotlight.png", // 40x40
  "ios_spotlight_2x": "resources/icons/ios_spotlight_2x.png", // 80x80
  "android_mdpi": "resources/icons/android_mdpi.png", // 48x48
  "android_hdpi": "resources/icons/android_hdpi.png", // 72x72
  "android_xhdpi": "resources/icons/android_xhdpi.png", // 96x96
  "android_xxhdpi": "resources/icons/android_xxhdpi.png", // 144x144
  "android_xxxhdpi": "resources/icons/android_xxxhdpi.png" // 192x192
});
```

I need to know the new list of icon/splash sizes and how Meteor names these for conversion.

Thanks!

**Comment by lpender** [comment]
This looks like an issue with Meteor--I opened an issue ^^
