### ISSUE TITLE
Issues with gm

### ISSUE THREAD

**Issue by braadworst** [lpender/meteor-assets#3]
I had some issues with gm:

Could not execute GraphicsMagick/ImageMagick: convert "resources/splash.png" "-resize" "960x960" "-crop" "640x960+160+0" "resources/splashes/iphone_2x.png" this most likely means the gm/convert binaries can't be found]

Installed and reinstalled ImageMagicks and the whole sjebang, but it turned out 

.subClass({imageMagick: true}) in (meteor-assets.js)

Was the problem, removed it and it worked like a charm

**Comment by lpender** [comment]
Thats strange -- I tried your way and got errors.

I thought maybe the issue was with the `gm` version, but the `package.json` says `"gm": "^1.21.1"` and the latest `gm` is `1.21.1`.

What platform are you using?

I'm OS X

**Comment by jschlieber** [comment]
Maybe you should mention in the docs, that imagemagick must be installed. It took me a while to figure that out ;)

```
sudo apt-get install imagemagick imagemagick-doc
```

Thanks for sharing this tool!

**Comment by lpender** [comment]
Ok, added: 
https://github.com/lpender/meteor-assets/commit/86ff971a560c92918e10fe811ad17c0951baa7ac

Thanks
